extends: ['@r1oga']
parserOptions:
  project:
    [
      'tsconfig.json',
      'apis/query/tsconfig.json',
      'circuits/circom/tsconfig.json',
    ]

overrides:
  - files: ['apis/query/test/unit/QueryService.test.ts']
    rules:
      '@typescript-eslint/ban-ts-comment': 'off'
  - files: ['apis/query/test/unit/AnonymitySetController.test.ts']
    rules:
      jest/expect-expect: 'off'
