extends: ['@3pwd/eslint-config-with-jest']
parserOptions:
  project:
    [
      'tsconfig.json',
      'apis/prove/tsconfig.json',
      'apis/query/tsconfig.json',
      'circuits/circom/tsconfig.json',
      'demo/tsconfig.json',
      'docs/tsconfig.json',
      'membership/tsconfig.json',
      'ui/tsconfig.json',
    ]

rules:
  no-useless-constructor: off

overrides:
  - files: ['membership/test/ProofRequest.test.ts']
    rules:
      '@typescript-eslint/dot-notation': off
  - files: ['apis/prove/src/mq/queue.ts']
    rules:
      '@typescript-eslint/strict-boolean-expressions': off
  - files:
      [
        'demo/src/cli/index.ts',
        'apis/prove/src/mq/processor.ts',
        'apis/prove/src/mq/worker.ts',
        'membership/src/ProofRequest/index.ts',
        'membership/test/ProofRequest.test.ts',
      ]
    rules:
      '@typescript-eslint/restrict-template-expressions': off
  - files:
      [
        'apis/query/src/api/controllers/requests/getEthBalanceAnonSetQuery.ts',
        'apis/query/src/api/repositories/DuneRepository.ts',
      ]
    rules:
      '@typescript-eslint/no-inferrable-types': off
  - files: ['apis/prove/generated/*.js']
    rules:
      eqeqeq: off
  - files: ['apis/prove/generated/witness_calculator.js']
    env:
      browser: true
    rules:
      prefer-const: off
      camelcase: off
  - files: ['apis/prove/generated/generate_witness.js']
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['*.tsx']
    rules:
      '@typescript-eslint/no-misused-promises':
        [error, { checksVoidReturn: { attributes: false } }]
  - files: ['apis/prove/src/routes.ts']
    rules:
      '@typescript-eslint/no-misused-promises': off
  - files:
      [
        'demo/src/cli/index.ts',
        'apis/*/src/index.ts',
        'apis/prove/generated/*.js',
        'apis/prove/src/mq/*.ts',
        'demo/src/index.ts',
      ]
    rules:
      no-console: off
  - files: ['apis/query/src/decorators/Logger.ts']
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
  - files:
      [
        'apis/query/test/unit/QueryService.test.ts',
        'apis/query/src/decorators/Logger.ts',
      ]
    rules:
      '@typescript-eslint/ban-ts-comment': 'off'
  - files:
      [
        'apis/query/test/unit/*Controller.test.ts',
        'circuits/circom/test/circuit.test.ts',
      ]
    rules:
      jest/expect-expect: 'off'
  - files: ['shared/src/index.ts']
    rules:
      'sort/exports': 'off'
