extends: ['@sripwoud/eslint-config-with-jest']
parserOptions:
  project:
    [
      'circom/tsconfig.json',
      'discord-bot/tsconfig.json',
      'pkgs/merkle-tree-worker/tsconfig.json',
      'pkgs/proof/tsconfig.json',
      'pkgs/query/tsconfig.json',
      'pkgs/spartan-ecdsa-worker/tsconfig.json',
      'query-api/tsconfig.json',
      'test/tsconfig.json',
      'ui/tsconfig.json',
      'tsconfig.json',
    ]

rules:
  no-useless-constructor: off

overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      '@typescript-eslint/await-thenable': error
  - files: ['query-api/test/unit/DuneRepository.test.ts']
    rules:
      '@typescript-eslint/no-dynamic-delete': off
  - files: ['*.ts']
    rules:
      '@typescript-eslint/dot-notation': off # because using noPropertyAccessFromIndexSignature tsc option
  - files: ['test/jest-preset.js']
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['pkgs/proof/test/ProofRequest.test.ts']
    rules:
      '@typescript-eslint/dot-notation': off
  - files:
      [
        'pkgs/cli/src/cli/index.ts',
        'pkgs/proof/src/ProofRequest/index.ts',
        'pkgs/proof/test/ProofRequest.test.ts',
      ]
    rules:
      '@typescript-eslint/restrict-template-expressions': off
  - files:
      [
        'query-api/src/api/controllers/requests/getEthBalanceAnonSetQuery.ts',
        'query-api/src/api/repositories/DuneRepository.ts',
      ]
    rules:
      '@typescript-eslint/no-inferrable-types': off
  - files: ['*.tsx']
    rules:
      '@typescript-eslint/no-misused-promises':
        [error, { checksVoidReturn: { attributes: false } }]
  - files:
      [
        'pkgs/cli/src/{,Cli/}index.ts',
        'circom/scripts/*.ts',
        'query-api/src/index.ts',
        'ui/src/lib/config.ts',
        'discord-bot/src/{index,events/{ClientReady,MessageCreate}}.ts',
      ]
    rules:
      no-console: off
  - files: ['query-api/src/decorators/Logger.ts']
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
  - files:
      [
        'query-api/test/unit/QueryService.test.ts',
        'query-api/src/decorators/Logger.ts',
      ]
    rules:
      '@typescript-eslint/ban-ts-comment': 'off'
  - files:
      ['circom/test/circuit.test.ts', 'query-api/test/unit/*Controller.test.ts']
    rules:
      jest/expect-expect: 'off'
  - files: ['pkgs/cli/src/Prompt/index.ts']
    rules:
      '@typescript-eslint/naming-convention': off
