extends: ['@r1oga']
parserOptions:
  project:
    [
      'tsconfig.json',
      'apis/proving/tsconfig.json',
      'apis/query/tsconfig.json',
      'circuits/circom/tsconfig.json',
      'demo/tsconfig.json',
      'docs/tsconfig.json',
      'shared/tsconfig.json',
    ]

rules:
  no-useless-constructor: off

overrides:
  - files:
      ['apis/query/src/api/controllers/requests/getEthBalanceAnonSetQuery.ts']
    rules:
      '@typescript-eslint/no-inferrable-types': off
  - files: ['apis/proving/generated/*.js']
    rules:
      eqeqeq: off
  - files: ['apis/proving/generated/witness_calculator.js']
    env:
      browser: true
    rules:
      prefer-const: off
      camelcase: off
  - files: ['apis/proving/generated/generate_witness.js']
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['apis/proving/src/routes.ts']
    rules:
      '@typescript-eslint/no-misused-promises': off
  - files:
      [
        'apis/*/src/index.ts',
        'apis/proving/generated/*.js',
        'demo/src/index.ts',
      ]
    rules:
      no-console: off
  - files: ['apis/query/src/decorators/Logger.ts']
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
  - files:
      [
        'apis/query/test/unit/QueryService.test.ts',
        'apis/query/src/decorators/Logger.ts',
      ]
    rules:
      '@typescript-eslint/ban-ts-comment': 'off'
  - files:
      [
        'apis/query/test/unit/*Controller.test.ts',
        'circuits/circom/test/circuit.test.ts',
      ]
    rules:
      jest/expect-expect: 'off'
  - files: ['shared/src/index.ts']
    rules:
      'sort/exports': 'off'
