extends: ['@sripwoud/eslint-config-with-jest']
parserOptions:
  project:
    [
      '@anonklub/proof/tsconfig.json',
      '@anonklub/cli/tsconfig.json',
      '@anonklub/query/tsconfig.json',
      'circuits/circom/tsconfig.json',
      'discord-bot/tsconfig.json',
      'infra/tsconfig.json',
      'test/tsconfig.json',
      'query-api/tsconfig.json',
      'ui/tsconfig.json',
      'tsconfig.json',
      'workers/merkle-tree-worker/tsconfig.json',
      'workers/spartan-ecdsa-worker/tsconfig.json',
    ]

rules:
  no-useless-constructor: off

overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      '@typescript-eslint/await-thenable': error
  - files: ['query-api/test/unit/DuneRepository.test.ts']
    rules:
      '@typescript-eslint/no-dynamic-delete': off
  - files: ['*.ts']
    rules:
      '@typescript-eslint/dot-notation': off # because using noPropertyAccessFromIndexSignature tsc option
  - files: ['test/jest-preset.js']
    rules:
      '@typescript-eslint/no-var-requires': off
  - files: ['@anonklub/proof/test/ProofRequest.test.ts']
    rules:
      '@typescript-eslint/dot-notation': off
  - files:
      [
        '@anonklub/cli/src/cli/index.ts',
        'infra/resources/config.ts',
        '@anonklub/proof/src/ProofRequest/index.ts',
        '@anonklub/proof/test/ProofRequest.test.ts',
      ]
    rules:
      '@typescript-eslint/restrict-template-expressions': off
  - files:
      [
        'query-api/src/api/controllers/requests/getEthBalanceAnonSetQuery.ts',
        'query-api/src/api/repositories/DuneRepository.ts',
      ]
    rules:
      '@typescript-eslint/no-inferrable-types': off
  - files: ['*.tsx']
    rules:
      '@typescript-eslint/no-misused-promises':
        [error, { checksVoidReturn: { attributes: false } }]
  - files: ['apis/prove/src/routes.ts']
    rules:
      '@typescript-eslint/no-misused-promises': off
  - files:
      [
        'circuits/circom/scripts/*.ts',
        '@anonklub/cli/src/index.ts',
        '@anonklub/cli/src/Cli/index.ts',
        'query- api/src/index.ts',
        'ui/src/lib/config.ts',
      ]
    rules:
      no-console: off
  - files: ['query-api/src/decorators/Logger.ts']
    rules:
      '@typescript-eslint/no-explicit-any': 'off'
  - files:
      [
        'query-api/test/unit/QueryService.test.ts',
        'query-api/src/decorators/Logger.ts',
      ]
    rules:
      '@typescript-eslint/ban-ts-comment': 'off'
  - files:
      [
        'query-api/test/unit/*Controller.test.ts',
        'circuits/circom/test/circuit.test.ts',
      ]
    rules:
      jest/expect-expect: 'off'
  - files: ['shared/src/index.ts']
    rules:
      'sort/exports': 'off'
  - files: ['@anonklub/cli/src/Prompt/index.ts']
    rules:
      '@typescript-eslint/naming-convention': off
