[workspace]
resolver = "2"
default-members = ["pkgs/cli"]
members = [
    "pkgs/cli",
    "pkgs/circuits/halo2",
    "pkgs/merkle-tree-wasm",
    "pkgs/spartan-ecdsa-wasm"
]

[profile.release]
lto = true
opt-level = 3
