[workspace]
resolver = "2"
default-members = ["pkgs/cli"]
members = [
    "pkgs/cli",
    "pkgs/circuits/halo2",
    "pkgs/merkle-tree-wasm",
    "pkgs/spartan-ecdsa-wasm", 
<<<<<<< HEAD
    "pkgs/circuits/halo2wrong-ecdsa"
=======
    "pkgs/circuits/halo2-ecdsa"
>>>>>>> f50031f (feat: adding halo2wrong ecdsa verison circuit wip)
]

[profile.release]
lto = true
opt-level = 3
