packages:
  - '@anonklub/*'
  - circuits/*
  - circuits/spartan/*
  - contracts
  - discord-bot
  - infra
  - test
  - ui
  - merkle-tree-wasm
  - merkle-tree-wasm/wasm-pkg
  - query-api
  - workers/*
