app = "anonklub-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
build-target = "deploy"

[env]
GUILD_ID = 1268958308249637017
UI_URL = "https://anonklub.xyz"
VERIFICATION_CHANNEL_ID = 1268958345130414241
VERIFIED_ROLE_ID = 1268958408510279932

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 3000
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
