[package]
name = "halo2-eth-membership"
version = "0.1.0"
authors = ["0xisk"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
bincode = "1.3.3"
ethers = "2.0.11"
halo2-base = { version = "0.4.1", default-features = false, features = ["halo2-axiom"] }
halo2-binary-merkle-tree = { path = "../halo2-binary-merkle-tree" }
halo2-ecc = { version = "0.4.1", default-features = false, features = ["halo2-axiom"] }
halo2-ecdsa = { path = "../halo2-ecdsa" }
halo2-wasm = { version = "0.3.4", default-features = false }
halo2-wasm-ext = { path = "../halo2-wasm-ext" }
hex = "0.4"
itertools = "0.13.0"
libsecp256k1 = "0.7"
num-bigint = "0.4.4"
pse-poseidon = { git = "https://github.com/aerius-labs/pse-poseidon.git", branch = "feat/stateless-hash" }
rand = "0.8"
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
serde = { version = "1.0.188", features = ["derive"] }
serde-wasm-bindgen = "0.6.4"
serde_json = "1.0"
snark-verifier = { version = "0.1.7", default-features = false, features = ["loader_halo2", "halo2-axiom"] }
snark-verifier-sdk = { version = "0.1.7", default-features = false, features = ["loader_halo2", "halo2-axiom"] }
subtle = "2.5"
wasm-bindgen = "0.2.89"

[features]
default = ["rayon"]
rayon = ["halo2-wasm/rayon"]
