[package]
name = "halo2-eth-membership"
version = "0.1.0"
edition = "2021"
authors = ["0xisk"]

build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
halo2-ecc = { version = "0.4.1", default-features = false, features = ["halo2-axiom"] }
halo2-base = { version = "0.4.1", default-features = false, features = ["halo2-axiom"] }
halo2-wasm = { version = "0.3.4" }
halo2-wasm-ext = { path = "../halo2-wasm-ext" }
halo2-ecdsa = { path = "../halo2-ecdsa" }
halo2-binary-merkle-tree = { path = "../halo2-binary-merkle-tree" }
pse-poseidon = { git = "https://github.com/aerius-labs/pse-poseidon.git", branch = "feat/stateless-hash" }
wasm-bindgen = "0.2.89"
serde-wasm-bindgen = "0.6.4"
getrandom = { version = "0.2", features = ["js"] }
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
rand = "0.8"
serde_json = "1.0"
serde = { version = "1.0.188", features = ["derive"] }
num-bigint = "0.4.4"
anyhow = "1.0.81"
bincode = "1.3.3"
hex = "0.4"
libsecp256k1 = "0.7"
ethers = "2.0.11"
subtle = "2.5"
itertools = "0.13.0"
snark-verifier-sdk = { version = "0.1.7", default-features = false, features = ["loader_halo2", "halo2-axiom"] }
snark-verifier = { version = "0.1.7", default-features = false, features = ["loader_halo2", "halo2-axiom"] }
tiny-keccak = "2.0"
log = "0.4"
gloo-utils = "0.2"
reqwest = { version = "0.11", features = ["json", "blocking"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
tokio = { version = "1", features = ["full"] }

[features]
default=["rayon"]
rayon=["halo2-wasm/rayon"]
