[package]
name = "akli"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
description = "A simple grep clone written in Rust"
readme = "README.md"
homepage = "https://github.com/sripwoud/grrs"
repository = "https://github.com/sripwoud/grrs"
keywords = ["cli", "search", "demo"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "akli"
path = "bin/main.rs"

[dependencies]
anyhow = "1.0.80"
async-std = { version="1.12.0", features = ["attributes"] }
clap = { version = "4.5.1", features = ["derive"] }
clap-verbosity-flag = "2.2.0"
env_logger = "0.11.2"
indicatif = "0.17.8"
log = "0.4.20"
serde = "1.0.197"
serde_json = "1.0.114"
surf = "2.3.2"

[dev-dependencies]
assert_cmd = "2.0.14"
assert_fs = "1.1.1"
predicates = "3.1.0"
