[package]
name = "akli"
version = "0.1.0"
authors = ["sripwoud"]
categories = ["command-line-utilities"]
documentation = "https://github.com/anonklub/anonklub/tree/main/pkgs/cli/README.md"
edition = "2021"
exclude = ["tests/*", "justfile"]
homepage = "https://github.com/anonklub/anonklub/tree/main/pkgs/cli/"
keywords = ["ethereum", "anonymity", "query", "set", "data"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/anonklub/anonklub/tree/main/pkgs/cli"
description = "Command line to interact with anonklub query api (https://query.anonklub.xyz)."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "akli"
path = "bin/main.rs"

[dependencies]
alloy-primitives = "0.6.0"
anyhow = "1.0.80"
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.5.1", features = ["derive"] }
clap-verbosity-flag = "2.2.0"
derive_more = "0.99.17"
env_logger = { version = "0.11.2", default-features = false }
indicatif = "0.17.8"
log = "0.4.20"
merkle-tree-wasm = { version = "1.1.1", path = "../merkle-tree-wasm" }
mockito = "1.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.114"
strum = { version = "0.26.2", features = ["derive"] }
surf = "2.3.2"
[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
