[package]
name = "halo2-ecdsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }

# halo2
halo2 = { package = "halo2_proofs", git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v0.3.0" }
halo2wrong = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git" }
maingate = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git" }
integer = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git" }
ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", default-features = false }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false }
