[package]
name = "merkle-tree-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-secq256k1 = "0.4.0"
ark-serialize = "0.4.2"
ark-std = "0.4.0"
console_error_panic_hook = "0.1.7"
csv = "1.3.0"
hex = "0.4.3"
num-bigint = "0.4.4"
poseidon = { git = "https://github.com/personaelabs/poseidon" }
rayon = "1.8.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3.66", features = ["console"] }

[dev-dependencies]
ark-std = "0.4.0"

[features]
default = ["ark-std/print-trace"]

[profile.release]
lto = true
opt-level = 3
