[package]
name = "halo2-e2e"
version = "0.1.0"
authors = ["0xisk"]
edition = "2021"

[dependencies]
anyhow = "1.0.81"
halo2-eth-membership = { path = "../halo2-eth-membership" }
reqwest = { version = "0.12.7" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
