[package]
name = "halo2-e2e"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2-eth-membership = { path = "../halo2-eth-membership" }
anyhow = "1.0.81"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0"
