sources:
  - name: ens-governance
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${GRAPH_API_KEY}/subgraphs/id/F7MznC87sv5y5jNUaBSrKFgCqTqP9Vgc11xcreZQpX7e
  - name: cryptopunks
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/${GRAPH_API_KEY}/subgraphs/id/YqMJatbgbqy1GodtbYZv4U9NzyaScCgSF7CAE5ivAM7

documents:
  - proposal-voters.graphql
  - punk.graphql
