[package]
name = "halo2-wasm-ext"
version = "0.1.0"
edition = "2021"
authors = ["0xisk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-ecc = { version = "0.4.1" }
halo2-base = { version = "0.4.1"}
halo2-wasm = { version = "0.3.4"}
wasm-bindgen = "0.2.87"
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
rand = "0.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
num-bigint = "0.4.4"
anyhow = "1.0.81"
bincode = "1.3.3"
hex = "0.4"
libsecp256k1 = "0.7"
ethers = "2.0.11"
subtle = "2.5"
itertools = "0.13.0"
snark-verifier-sdk = { version = "0.1.7", default-features = false, features = ["loader_halo2", "halo2-axiom"] }
# snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier.git", branch = "main", default-features = false, features = ["loader_halo2", "halo2-axiom"] }
snark-verifier = { version = "0.1.7", default-features = false, features = ["loader_halo2", "halo2-axiom"] }
# snark-verifier = { git = "https://github.com/axiom-crypto/snark-verifier.git", branch = "main", default-features = false, features = ["loader_halo2", "halo2-axiom"] }

[features]
default = ["rayon"]
rayon = ["halo2-wasm/rayon"]
