FROM node:19-alpine

RUN apk update
RUN apk add bash

RUN npm i -g pnpm

WORKDIR app

COPY package.json ./
RUN echo "auto-install-peers=true" > .npmrc

RUN pnpm i

COPY tsconfig.json .
COPY src src

EXPOSE 3000

COPY secrets-entrypoint.sh /usr/local/bin/secrets-entrypoint.sh
RUN chmod +x /usr/local/bin/secrets-entrypoint.sh
ENTRYPOINT ["secrets-entrypoint.sh"]

CMD ["pnpm", "run", "start.dev"]
