FROM node:19-alpine

RUN apk update
RUN apk add bash

RUN npm i -g pnpm

WORKDIR app

COPY package.json ./
RUN echo "auto-install-peers=true" > .npmrc

RUN pnpm i -P --ignore-scripts --reporter=silent

COPY tsconfig.json .
COPY dist dist

EXPOSE 3000

CMD ["pnpm", "run", "start.prod"]
