version: "3.9"

services:
   query-api:
     build: .
     environment:
       GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/google_credentials
       GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
     secrets:
       - google_credentials
     ports:
       - "3000:3000"

secrets:
   google_credentials:
     file: .keys.json

