version: '3.9'

services:
  query-api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      GOOGLE_APPLICATION_CREDENTIALS_FILE: /run/secrets/google_credentials
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      DUNE_USERNAME: ${DUNE_USER}
      DUNE_PASSWORD_FILE: /run/secrets/dune_password
      GRAPH_API_KEY_FILE: /run/secrets/graph_api_key
    secrets:
      - google_credentials
      - dune_password
      - graph_api_key
    ports:
      - '3000:3000'
    env_file:
      - .env

secrets:
  google_credentials:
    file: .key.json
  dune_password:
    file: .dune_pwd
  graph_api_key:
    file: .graph_api_key
