app = "anonset-staging"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
