openapi: 3.0.3
info:
  title: Anonnymity Set API
  description: Anonnymity Set API
  version: 1.0.0
  license:
    name: MIT
    url: 'https://github.com/privacy-scaling-explorations/e2e-zk-ecdsa/blob/main/LICENSE'
  contact:
    name: Privacy Scaling Explorations
    url: 'https://appliedzkp.org/'
  externalDocs:
    description: 'GitHub repository'
    url: 'https://github.com/privacy-scaling-explorations/e2e-zk-ecdsa/tree/main/apis/query'
servers:
  - url: 'https://anon-set.fly.dev'
    description: 'Production server'
  - url: 'https://anon-set-staging.fly.dev'
    description: 'Staging server'
paths:
  /balance/ETH:
    get:
      tags:
        - balance
      summary: List addresses that have a minimum balance of ETH.
      description: ''
      operationId: getEthBalanceAnonSet
      parameters:
        - name: min
          in: query
          description: Minimum ETH amount the addresses must have.
          required: true
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: ethereum addresses part of the anonymity set
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /balance/ERC20:
    get:
      tags:
        - balance
      summary: List addresses that have a minimum balance of some ERC20.
      description: ''
      operationId: getErc20BalanceAnonSet
      parameters:
        - name: tokenAddress
          in: query
          description: The address of the ERC20 token.
          required: true
          schema:
            type: string
        - name: min
          in: query
          description: Minimum ERC20 amount the addresses must have.
          required: true
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: ethereum addresses part of the anonymity set
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /beacon:
    get:
      tags:
        - beacon
      summary: List addresses that have deposited into the beacon contract.
      description: ''
      operationId: getBeaconAnonSet
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: ethereum addresses part of the anonymity set
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /punks:
    get:
      tags:
        - nft
      summary: List addresses that have deposited into the beacon contract.
      description: ''
      operationId: getPunksAnonSet
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: ethereum addresses part of the anonymity set
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /ens-proposal-voters:
    get:
      tags:
        - dao
      summary: List addresses that participated in an on chain ENS governance decision.
      description: ''
      operationId: getEnsVotersAnonSet
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: ethereum addresses part of the anonymity set
        '400':
          description: Invalid request
        '500':
          description: Internal server error
