#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check for staged .js or .ts files
if git diff --cached --name-only | grep -E '\.(js|ts|rs|circom|json|tsx)$'; then
    # Run tests if .js or .ts files are found
    CI=true pnpm run githook:prepush
else
    echo "No JavaScript or TypeScript files changed, skipping tests."
fi
