extends: ['../.eslintrc.yaml', 'next']
rules:
  '@next/next/no-html-link-for-pages': off # using app router, so no pages dir to check

overrides:
  - files: ['src/app/verify/result/page.tsx']
    rules:
      '@typescript-eslint/no-var-requires': off
