extends: ['../.eslintrc.yaml', 'next']
parserOptions:
  project: ['tsconfig.json']

rules:
  '@next/next/no-html-link-for-pages': off # using app router, so no pages dir to check

overrides:
  - files: ['src/app/verify/result/page.tsx', 'src/hooks/useVerifyProof.ts']
    rules:
      '@typescript-eslint/no-var-requires': off
