[package]
name = "merkle-tree-halo2"
version = "1.1.1"
edition = "2021"
license = "AGPL-3.0"
authors = ["0xisk"]
repository = "https://github.com/anonklub/anonklub/tree/main/pkgs/merkle-tree-halo2"
description = "Creation and management of Binary Merkle tree structures for Halo2 circuits."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib","cdylib"]

[dependencies]
pse-poseidon = { git = "https://github.com/aerius-labs/pse-poseidon.git", branch = "feat/stateless-hash" }
anyhow = "1.0.81"
halo2-ecc = { version = "0.4.1" }
halo2-base = { version = "0.4.1"}
halo2-wasm = { version = "0.3.4"}
console_error_panic_hook = "0.1.7"
csv = "1.3.0"
hex = "0.4.3"
num-bigint = "0.4.4"
rayon = "1.8.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3.66", features = ["console"] }

[dev-dependencies]
ark-std = "0.4.0"

[features]
default = ["ark-std/print-trace"]
