name: Coverage Report
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR comments
  pull_request:
    branches: [main, staging]
    paths: ['apis/**', 'circuits/**', '!**/*md', '!**/*yaml', '!**/*yml']
  push:
    branches: [main, staging]
    paths: ['apis/**', 'circuits/**', '!**/*md', '!**/*yaml', '!**/*yml']

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install node deps
        run: pnpm i --ignore-scripts --reporter=silent

      - name: Run tests
        env:
          DUNE_API_KEY: foo
        run: pnpm t

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: ./apis/query
          github-token: ${{ secrets.GITHUB_TOKEN }}
