name: Coverage Report
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR comments
  pull_request:
  push:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install & Test
        working-directory: ./apis/query
        run: |
          pnpm i --ignore-scripts --reporter=silent
          pnpm run nps test.ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          base-path: ./apis/query
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./apis/query/coverage/lcov.info
