name: Deployment Query API - Staging
on:
  workflow_dispatch:
  push:
    branches: [staging]
    paths: ['apis/query/**', '!**/*.md', '.github/workflows/deploy-staging.yml']

jobs:
  deployment:
    environment:
      name: staging
      url: https://anonset-staging.fly.dev
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy \
            --config apis/query/fly-staging.toml \
            --dockerfile apis/query/Dockerfile \
            --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
