name: Deployment Query API - Production
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['apis/query/**', '!**/*.md']

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deployment:
    environment:
      name: production
      url: https://anon-set.fly.dev
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        working-directory: ./apis/query
        run: flyctl deploy --config fly-prod.toml
