name: Deployment Query API - Staging
on:
  workflow_dispatch:
  push:
    branches: [staging]
    paths:
      [
        'query-api/**',
        '!**/*.md',
        '.github/workflows/deploy-query-api-staging.yml',
      ]

jobs:
  deployment:
    environment:
      name: query-api-staging
      url: https://anonset-staging.fly.dev
    name: Deploy Query API to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy \
            --config query-api/fly-staging.toml \
            --dockerfile query-api/Dockerfile \
            --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
