name: Deployment Discord Bot - Staging
on:
  workflow_dispatch:
  push:
    branches: [staging]
    paths:
      [
        "discord-bot/**",
        ".github/workflows/deploy-discord-bot-staging.yml",
        "!**/*.md",
      ]

jobs:
  deployment:
    environment:
      name: discord-bot-staging
    name: Deploy Discord Bot to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy \
            --config discord-bot/fly-staging.toml \
            --dockerfile discord-bot/Dockerfile \
            --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
