name: Deployment Discord Bot - Prod
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      [
        'discord-bot/**',
        '.github/workflows/deploy-discord-bot-prod.yml',
        '!**/*.md',
      ]

jobs:
  deployment:
    environment:
      name: discord-bot-prod
    name: Deploy Discord Bot to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy \
            --config discord-bot/fly-prod.toml \
            --dockerfile discord-bot/Dockerfile \
            --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
