name: Static Analysis demo
on:
  pull_request:
    branches: [main, staging]
    paths: ['demo/**']
  push:
    paths: ['demo/**']
jobs:
  validate:
    uses: ./.github/workflows/static-analysis.yml
    with:
      packages: 'demo'
    secrets: inherit
