name: Static Analysis circom
on:
  pull_request:
    paths: [
        'circom/**',
        '!**.circom', # eslint and prettier can't handle circom files
        '!**.sh',
      ]
  push:
    paths: ['circom/**', '!**.circom', '!**.sh']
jobs:
  validate:
    uses: ./.github/workflows/static-analysis.yml
    with:
      packages: 'circom'
    secrets: inherit
