name: Static Analysis
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', '**/public/**', '**/.*ignore', '**/*.toml']

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # TODO: skip tasks if unaffected https://turbo.build/repo/docs/core-concepts/monorepos/skipping-tasks
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly
      - name: Install wasm-pack
        uses: taiki-e/cache-cargo-install-action@v2.0.1
        with:
          tool: wasm-pack
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4.0.0
        id: pnpm-install
        with:
          version: 9.4.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Setup turbo cache
        id: turbo-cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install
        run: pnpm i --ignore-scripts --no-frozen-lockfile

      - name: Lint || Format || Build
        env:
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
          # just to allow next build to pass
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: foo
          NEXT_PUBLIC_QUERY_API_URL: 'https://anonset-staging.fly.dev'
          NEXT_PUBLIC_VERIFIER_ADDRESS: '0x123'
          NEXT_PUBLIC_VERIFIER_CHAIN_ID: 123
        run: pnpm validate
