name: Static Analysis docs
on:
  pull_request:
    branches: [main, staging]
    paths: ['docs/**', '!docs/static/**']
  push:
    paths: ['docs/**', '!docs/static/**']
jobs:
  validate:
    uses: ./.github/workflows/static-analysis.yml
    with:
      packages: 'docs'
    secrets: inherit
