name: Static Analysis
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: ['**/Dockerfile', 'apis/prove/generated/**', '**/public/**']
  push:
    branches: [main, staging]
    paths-ignore: ['**/Dockerfile', 'apis/prove/generated/**', '**/public/**']

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          version: 8.6.0
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Setup turbo cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install
        run: pnpm i --ignore-scripts

      - name: Lint || Format || Build
        env:
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
          NEXT_PUBLIC_NODE_ENV: test
        run: pnpm validate
