name: static analysis
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      [
        '**/Dockerfile',
        'apis/prove/generated/**',
        '**/public/**',
        '**/.*ignore',
        '**/*.toml',
      ]
  push:
    branches: [main, staging]
    paths-ignore:
      [
        '**/Dockerfile',
        'apis/prove/generated/**',
        '**/public/**',
        '**/.*ignore',
        '**/*.toml',
      ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # TODO: skip tasks if unaffected https://turbo.build/repo/docs/core-concepts/monorepos/skipping-tasks
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.1.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          version: 8.6.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Setup turbo cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Build Rust wasm deps
        run: pnpm compile.wasm

      - name: Install
        run: pnpm i --ignore-scripts --no-frozen-lockfile

      - name: Lint || Format || Build
        env:
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
          # just to allow next build to pass
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: foo
          NEXT_PUBLIC_QUERY_API_URL: bar
          NEXT_PUBLIC_PROVE_API_URL: baz
          NEXT_PUBLIC_VERIFIER_ADDRESS: '0x123'
          NEXT_PUBLIC_VERIFIER_CHAIN_ID: 123
        # force building @anonklub/proof package instead of hitting cache (as it is a dep of other local packages)
        run: |
          pnpm --filter @anonklub/proof build
          pnpm validate
