name: test
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request trigger required to get PR comments
  workflow_dispatch:
  pull_request:
    branches: [main, staging]
    paths:
      [
        'pkgs/**/*.{json,ts}',
        'contracts/**/*.sol',
        'query-api/**/*.{js,json,ts,graphql}',
        'test/**/*.{js,ts}',
        'pnpm-lock.yaml',
        '!**/*.md',
      ]
  push:
    branches: [main, staging]
    paths:
      [
        'pkgs/**/*.{json,ts}',
        'contracts/**/*.sol',
        'test/**/*.{js,ts}',
        'query-api/**/*.{js,json,ts,graphql}',
        'pnpm-lock.yaml',
        '!**/*.md',
      ]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install node deps
        run: pnpm i --ignore-scripts

      - name: Run tests
        env:
          DUNE_API_KEY: foo
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }} # required for build step on which test depends on
        run: pnpm test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
